### ISSUE TITLE
Hello! How can i multiple node object? I mean every time i have to click on that yellow circle to put one, but i need to click on yellow circle one time and put nodes nonstopable

### ISSUE THREAD

**Issue by alibekp** [fberasategui/WPFSamples#3]

**Comment by fberasategui** [comment]
Simply comment [this line](https://github.com/High-Core/WPFSamples/blob/master/src/WPFSamples/Samples/NodesEditor/NodesEditor.xaml.cs#L88)

**Comment by alibekp** [comment]
I've solved this question.
Now i have another one. How can i add my own objects besides yellow node?
And when i open NodesEditor i need to see empty map without already created nodes

**Comment by fberasategui** [comment]
@alibekp have a look at the other example, the HousePlan editor. Which is very similar, but has more custom diagram templates
